name: Deploy

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - main
  pull_request_target:
    branches:
      - main

permissions:
  checks: read
  contents: read
  pull-requests: read

jobs:
  wait-for-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for build and test checks
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          check-name: build_and_test
          repo-token: ${{ secrets.PAT_TOKEN }}
          wait-interval: 20
          allowed-conclusions: success
          running-workflow-name: Deploy

      - name: Wait for lint checks
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          check-name: lint
          repo-token: ${{ secrets.PAT_TOKEN }}
          wait-interval: 20
          allowed-conclusions: success
          running-workflow-name: Deploy

  deploy:
    needs: [wait-for-checks]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa
          known_hosts: unnecessary
          if_key_exists: replace

      - name: Add to known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRODUCTION_SERVER }} ssh-ed25519 SHA256:t88ooFTKGnCw0nAjfNjwX3p4RRsPfVV8ZZ6C4aJHAm4" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Test Connection
        run: |
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=accept-new ${{ secrets.PRODUCTION_USER }}@${{ secrets.PRODUCTION_SERVER }} 'echo "hello world"'
