name: Deploy

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - main
  pull_request_target:
    branches:
      - main

permissions:
  checks: read
  contents: read
  pull-requests: read

jobs:
  wait-for-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for build and test checks
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          check-name: build_and_test
          repo-token: ${{ secrets.PAT_TOKEN }}
          wait-interval: 20
          allowed-conclusions: success
          running-workflow-name: Deploy

      - name: Wait for lint checks
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          check-name: lint
          repo-token: ${{ secrets.PAT_TOKEN }}
          wait-interval: 20
          allowed-conclusions: success
          running-workflow-name: Deploy

  deploy:
    needs: [wait-for-checks]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create SSH key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa

      - name: Add known hosts
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
          ssh-keyscan -H ${{ secrets.PRODUCTION_SERVER }} >> ~/.ssh/known_hosts

      - name: Test connection
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.PRODUCTION_USER}}@${{ secrets.PRODUCTION_SERVER }} 'echo "hello from remote server"'
