name: Deploy

on:
  push:
    branches:
      - production
  pull_request: # TODO: Remove it before merge to main
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary
          if_key_exists: replace

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.PRODUCTION_SERVER }} >> ~/.ssh/known_hosts

      - name: Test Connection and Print Hello World
        run: ssh ${{ secrets.PRODUCTION_USER}}@${{ secrets.PRODUCTION_SERVER }} 'echo "hello world"'
