name: Deploy

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - main
  pull_request_target:
    branches:
      - main

permissions:
  checks: read
  contents: read
  pull-requests: read

jobs:
  wait-for-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for build and test checks
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          check-name: build_and_test
          repo-token: ${{ secrets.PAT_TOKEN }}
          wait-interval: 20
          allowed-conclusions: success
          running-workflow-name: Deploy

      - name: Wait for lint checks
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          check-name: lint
          repo-token: ${{ secrets.PAT_TOKEN }}
          wait-interval: 20
          allowed-conclusions: success
          running-workflow-name: Deploy

  deploy:
    needs: [wait-for-checks]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: |
            ${{ secrets.PRODUCTION_SERVER }}
          if_key_exists: replace

      - name: Add Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.PRODUCTION_SERVER }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Test Connection and Print Hello World
        run: |
          ssh -o StrictHostKeyChecking=no -v ${{ secrets.PRODUCTION_USER }}@${{ secrets.PRODUCTION_SERVER }} 'echo "hello world"'
