name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20

    - name: Install dependencies
      run: go mod download

    - name: Build
      run: make build

    - name: Setup mongodb 
      uses: supercharge/mongodb-github-action@1.9.0

    - name: Test
      run: make test
